### ISSUE TITLE
Checklist for v1.0.0 release

### ISSUE THREAD

**Issue by lopopolo** [artichoke/strftime-ruby#42]
This crate is looking pretty good and I think we can prepare to make a 1.0.0 release to crates.io.

@x-hgg-x do you think we're missing any API surface before we ship?

## Checklist

- [x] 100% coverage? I think we can get here by removing unused derives on private types.
- [x] API completeness
  - [x] `core::fmt::Write` destination
  - [x] `std::io::Write` destination
- [x] Add fuzzing
- [x] @lopopolo review docs for typos and completeness.
- [x] @x-hgg-x review docs for typos and completeness.
- [x] Bump crate version, README version, and docs HTML version to 1.0.0.
- [x] Prepare release notes.
- [x] Cut v1.0.0 tag.
- [x] Create v1.0.0 GitHub release.
- [x] Publish to crates.io.
- [x] Add @artichoke/crates-io-publishers as a crate owner on crates.io.
- [x] Add @x-hgg-x as a crate owner on crates.io.
- [x] Decide on release strategy for after 1.0.0.
- [x] Announce release on Reddit.
- [x] Announce release on Twitter.
- [x] Announce release on URLO.

**Comment by lopopolo** [comment]
I guess we might be missing APIs that write to a `&mut dyn core::fmt::Write` and `&mut dyn std::io::Write`.

I think we can do `io::Write` fairly easily by new typing the `Vec` we use in the `bytes` and `string` modules so it doesn't implement `io::Write` and then making a blanket impl of our `Write` trait for `io::Write`.

I'm not sure if `fmt::Write` is as easy though since the internals are all in terms of bytes.

**Comment by x-hgg-x** [comment]
I don't know: what should be the use case for this ? 

Is there an example of another crate which does the same thing ?

**Comment by lopopolo** [comment]
V0.4.x of `itoa` had an API like this.

**Comment by lopopolo** [comment]
@x-hgg-x experimented with a refactor to enable a `&mut dyn core::fmt::Write` API which we agreed to not merge due to the additional complexity:

- #46

**Comment by x-hgg-x** [comment]
> * [ ]  100% coverage? I think we can get here by removing unused derives on private types.

We can't really get to 100% coverage, since the `#[derive(Copy)]` for `Spec` is necessary but not associated to any code. 
All the `#[derive(Debug)]` are also still useful if we want to do some quick debugging with `println!`.

**Comment by lopopolo** [comment]
sounds good. I think we can check that box then since we've addressed the task and made a decision.

**Comment by lopopolo** [comment]
`std::io::Write` impl is here:

- https://github.com/artichoke/strftime-ruby/pull/49

thanks @x-hgg-x!

**Comment by lopopolo** [comment]
`core::fmt::Write` impl is here:

- https://github.com/artichoke/strftime-ruby/pull/50

It uses the same approach @x-hgg-x experimented with in #49.

**Comment by lopopolo** [comment]
I made several small last-minute fixups:

- https://github.com/artichoke/strftime-ruby/pull/56
- https://github.com/artichoke/strftime-ruby/pull/57
- https://github.com/artichoke/strftime-ruby/pull/59
- https://github.com/artichoke/strftime-ruby/pull/60

**Comment by lopopolo** [comment]
One last pass at the README:

- #55 

And the bump to v1.0.0! 🎉 

- #58

**Comment by lopopolo** [comment]
Found another tweak to the error enum:

- https://github.com/artichoke/strftime-ruby/pull/61

**Comment by lopopolo** [comment]
For announcements, I can tweet from `@artichokeruby`. I'll post the link here once I do.

I can also take the URLO announcement, but if if you'd like to do this I'm happy to give this task to you.

Could you take the post on Reddit?

**Comment by x-hgg-x** [comment]
I don't have an account on URLO, so I'm leaving it to you.
I will anyway make the announcement post on Reddit.

**Comment by lopopolo** [comment]
Crate is released and I invited you as an owner @x-hgg-x:

- https://crates.io/crates/strftime-ruby
- https://docs.rs/strftime-ruby

**Comment by lopopolo** [comment]
I think we're ready to announce

**Comment by lopopolo** [comment]
URLO post: https://users.rust-lang.org/t/announcing-strftime-ruby-v1-0-0/80146

**Comment by x-hgg-x** [comment]
Reddit post: https://www.reddit.com/r/rust/comments/wtbe4j/announcing_strftimeruby_v100_a_pure_rust_nostd/

**Comment by lopopolo** [comment]
Twitter thread: https://twitter.com/artichokeruby/status/1561031175287672832

**Comment by lopopolo** [comment]
I'll close this out and cut a ticket for us to discuss post-1.0.0 release cadence and strategy:

- https://github.com/artichoke/strftime-ruby/issues/66

**Comment by lopopolo** [comment]
Huge congrats I think are in order here. This is a great piece of work. Thanks @x-hgg-x for helping make this happen 🎉

**Comment by lopopolo** [comment]
I did a "Show HN" here: https://news.ycombinator.com/item?id=32535210

**Comment by Kijewski** [comment]
Congratulation! You all did very impressive work! strftime sucks very badly in most languages, but this looks like a very sane implementation. :)

**Comment by lopopolo** [comment]
This release and ownership status is reflected in https://github.com/artichoke/project-infrastructure/blob/ff3db053d666e20cd8c05fab9d52fa64be3f1f74/docs/crates.io.md as of:

- https://github.com/artichoke/project-infrastructure/pull/351
